---
title             : "Lab 8 Full Document"
shorttitle        : "Lab 8 Short Title"

author: 
  - name          : "Alexis Adams-Clark"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "2000 Oregon St."
    email         : "aadamscl@uoregon.edu"
  - name          : "Andrew Fridman"
    affiliation   : "1"
  - name          : "Xi Yang"
    affiliation   : "1"
    

affiliation:
  - id            : "1"
    institution   : University of Oregon


authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  I could not remove the author note!

abstract: |
  Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract.   Hello, this is the abstract. 
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "group project, R, github"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
